/**
 * BDK-CoreFinance API Gateway
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {HttpHeaders} from '@angular/common/http';

import {Observable} from 'rxjs';

import {
  GroupListResponse,
  GroupMembersResponse,
  IbanValidationResultDto,
  PartnerDto,
  PartnerGroupSearchResponse,
  PartnerSummaryDto,
  PostalCodeAreaFocusDto,
  SalesAreaDataResponse
} from '../model/models';


import {Configuration} from '../configuration';


export interface PartnerGatewayServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Get partner by number with complete information (Gateway Proxy)
   * Retrieves complete partner information including all contact persons, addresses, and telecommunication details. Proxied through gateway to partner service.
   * @param partnerNumber Partner number to retrieve
   */
  findByPartnerNumber(partnerNumber: number, extraHttpRequestParams?: any): Observable<PartnerDto>;

  /**
   * Get postal code area focus by postal code (Gateway Proxy)
   * Retrieves active postal code area focus information by postal code including regional data and focus indicators. Proxied through gateway to partner service.
   * @param postalCode Postal code to search for
   */
  findByPostalCode(postalCode: string, extraHttpRequestParams?: any): Observable<PostalCodeAreaFocusDto>;

  /**
   * Get all partner groups/associations (Gateway Proxy)
   * Retrieves a list of all partner groups. Proxied through gateway to partner service.
   */
  getAllGroups(extraHttpRequestParams?: any): Observable<GroupListResponse>;

  /**
   * Get members of a specific group (Gateway Proxy)
   * Retrieves all members of a partner group by group number using the CF_GET_GROUP_MEMBERS view. Proxied through gateway to partner service.
   * @param groupNumber Group number to find members for
   */
  getGroupMembers(groupNumber: string, extraHttpRequestParams?: any): Observable<GroupMembersResponse>;

  /**
   * Get partner summary by number (Gateway Proxy)
   * Retrieves partner summary information including advisor details, sales area information, branch details, and change tracking. Proxied through gateway to partner service.
   * @param partnerNumber Partner number to retrieve summary for
   */
  getPartnerSummary(partnerNumber: number, extraHttpRequestParams?: any): Observable<PartnerSummaryDto>;

  /**
   * Get sales area master data (Gateway Proxy)
   * Retrieves comprehensive sales area master data including all branch offices and active sales area focus entries. Proxied through gateway to partner service.
   */
  getSalesAreaData(extraHttpRequestParams?: any): Observable<SalesAreaDataResponse>;

  /**
   * Save partner data (Gateway Proxy)
   * Creates a new partner or updates an existing partner. If partner number is provided, an update will be performed. If no partner number is provided, a new partner will be created. Proxied through gateway to partner service.
   * @param partnerDto
   */
  savePartner(partnerDto: PartnerDto, extraHttpRequestParams?: any): Observable<PartnerDto>;

  /**
   * Combined partner and group search (Gateway Proxy)
   * Search for partners using comprehensive search criteria. Name field searches in name1/name2/name3 with AND logic. Use * for wildcard search in alphaCode, postcode, city, and street fields. All search fields except partnerNumber require minimum 3 characters. Proxied through gateway to partner service.
   * @param partnerNumber Partner number for exact match search
   * @param alphaCode Alpha code (3-10 characters). Use * for wildcard search
   * @param name Partner name for partial search in name fields 1-3 (3-35 characters)
   * @param postalCode Postcode (3-5 characters). Use * for wildcard search
   * @param city City (2-35 characters). Use * for wildcard search
   * @param street Street (3-35 characters). Use * for wildcard search
   */
  searchPartnersAndGroups(partnerNumber?: string, alphaCode?: string, name?: string, postalCode?: string, city?: string, street?: string, extraHttpRequestParams?: any): Observable<PartnerGroupSearchResponse>;

  /**
   * Validate IBAN and extract banking information (Gateway Proxy)
   * Validates an International Bank Account Number (IBAN) using country-specific configurations and extracts banking details including bank code, account number, bank name, and BIC code. Proxied through gateway to partner service.
   * @param iban IBAN to validate (spaces will be automatically removed)
   */
  validateIban(iban: string, extraHttpRequestParams?: any): Observable<IbanValidationResultDto>;

}
