services:
  npm-mirror:
    container_name: npm-mirror
    hostname: npm-mirror
    image: verdaccio/verdaccio-custom
    build:
      dockerfile: Dockerfile
    volumes:
      - verdaccio-storage:/verdaccio/storage
      - verdaccio-plugins:/verdaccio/plugins
    environment:
      - NODE_ENV=production
    ports:
      - 4873:4873
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:4873"]
      interval: 10s
      timeout: 5s
      retries: 1

volumes:
  verdaccio-storage:
  verdaccio-plugins:
